Repository geekymeeky/JS-games, pull requests merged in 2021-07, with the labels that each got.

#31 wall-breaker
  index.html
  static/css/wallbreaker.css
  static/images/WallBreaker/WallBreaker.png
  static/js/wallbreaker.js
  static/music/wallbreaker/gameover.mp3
  static/music/wallbreaker/move.mp3
  wallbreaker.html
Labels: needs-more-info

#48 added darkmode
  index.html
  static/css/style.css
  static/js/main.js
Labels: DCP21

#59 dino game
  dino.html
  index.html
  static/css/dino.css
  static/images/dino/bg.png
  static/images/dino/dino.png
  static/images/dino/dinogame.png
  static/images/dino/dragon.png
  static/js/dino.js
Labels: DCP21

#65 added flip-me game
  flips-me.html
  index.html
  static/css/flips-me.css
  static/images/flips-me/flip.jpg
  static/js/flips-me.js
Labels: DCP21, Level2

#67 fixed link
  snakegame.html
Labels: DCP21, Level0

#82 Added 3d-tic-tac-toe game
  3d-tictactoe.html
  index.html
  static/css/3d-tictactoe.css
  static/images/3d-tictactoe/background.png
  static/images/3d-tictactoe/logo.png
  static/images/3d-tictactoe/tictactoe.PNG
  static/js/3d-tictactoe.js
  static/music/3d-tictactoe/click.mp3
  static/music/3d-tictactoe/win.wav
Labels: DCP21, Level2, needs-more-info

#88 added preloader
  index.html
  static/css/style.css
  static/js/main.js
Labels: DCP21, Level2

#86 Added Flappy Bird
  flappy_bird.html
  index.html
  static/css/flappy_bird.css
  static/images/flappy_bird/bg.png
  static/images/flappy_bird/bird.png
  static/images/flappy_bird/enter.png
  static/images/flappy_bird/fg.png
  static/images/flappy_bird/flappy_bird.PNG
  static/images/flappy_bird/pipeNorth.png
  static/images/flappy_bird/pipeSouth.png
  static/js/flappy_bird.js
Labels: DCP21, Level3

#93 All games arranged
  index.html
Labels: DCP21, Level1

#87 Added Guess the number Game
  Guess_the_number.html
  index.html
  static/css/guess_the_number.css
  static/images/Guess the Number/guess the number.png
  static/js/guess_the_number.js
Labels: DCP21, Level2

#81 Added the 2048 Game the JS Games repo
  2048game.html
  index.html
  static/css/2048game.css
  static/images/2048game/2048game.png
  static/js/2048game.js
Labels: DCP21, Level3

#85 created reaction time game
  index.html
  reaction.html
  static/css/reaction.css
  static/images/reaction.PNG
  static/js/reaction.js
Labels: DCP21, Level2

#104 Random Joke Generator
  index.html
  randomJoke.html
  static/css/randomJoke.css
  static/images/randomJoke.jfif
  static/js/randomJoke.js
Labels: DCP21, Level2

#110 Fixed the bug
  static/css/style.css
Labels: DCP21, Level1

#117 Added the code for Space Shooter Game
  index.html
  space_shooter.html
  static/css/space_shooter.css
  static/images/space_shooter/background_ssg.png
  static/images/space_shooter/bullet_ssg.png
  static/images/space_shooter/enemy_ssg.png
  static/images/space_shooter/poster_ssg.png
  static/images/space_shooter/spaceship_ssg.png
  static/js/space_shooter.js
Labels: DCP21, Level3

#118 Added the Doodle Jump Game
  doodlejump.html
  index.html
  static/css/doodlejump.css
  static/images/doodlejump/background.png
  static/images/doodlejump/doodlejump.png
  static/images/doodlejump/doodler-guy.png
  static/images/doodlejump/platform.png
  static/images/doodlejump/playButton.png
  static/js/doodlejump.js
Labels: DCP21, Level3

#102 Flip me game
  flips-me.html
  index.html
  static/css/flip-me.css
  static/images/flip-me.JPG
  static/js/flip-me.js
Labels: DCP21, Level2

#119 Added Fall In Game
  Fall_game.html
  index.html
  static/css/Fall_game.css
  static/images/Fall_game/background.png
  static/images/Fall_game/brick.jpg
  static/images/Fall_game/pic.jpg
  static/js/Fall_game.js
Labels: DCP21, Level3
